# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arrive_time_widegt_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(937, 692)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tool_widget = QtWidgets.QWidget(Form)
        self.tool_widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.tool_widget.setObjectName("tool_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tool_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.tool_widget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_10 = QtWidgets.QPushButton(self.tool_widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_2 = QtWidgets.QPushButton(self.tool_widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.tool_widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.tool_widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.pushButton_7 = QtWidgets.QPushButton(self.tool_widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.tool_widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.tool_widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_11 = QtWidgets.QPushButton(self.tool_widget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.tool_widget)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setFrameShape(QtWidgets.QFrame.Box)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setObjectName("splitter")
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.pushButton_10.clicked.connect(Form.locate)
        self.pushButton_7.clicked.connect(Form.set_scale_x)
        self.pushButton_8.clicked.connect(Form.set_scale_y)
        self.pushButton_9.clicked.connect(Form.set_scale_xy)
        self.comboBox.currentTextChanged['QString'].connect(Form.set_stamp_name)
        self.pushButton_11.clicked.connect(Form.update_figs)
        self.pushButton.clicked.connect(Form.last)
        self.pushButton_3.clicked.connect(Form.next)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_10.setText(_translate("Form", "定位"))
        self.pushButton_2.setText(_translate("Form", "保存"))
        self.pushButton.setText(_translate("Form", "上一个"))
        self.pushButton_3.setText(_translate("Form", "下一个"))
        self.pushButton_7.setText(_translate("Form", "x轴"))
        self.pushButton_8.setText(_translate("Form", "y轴"))
        self.pushButton_9.setText(_translate("Form", "xy轴"))
        self.pushButton_11.setText(_translate("Form", "刷新窗口"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
